create slack-bot (raw version)
jehy/shodan pull request #14
Opened 2019-10-23 10:21 UTC by kotAndEgor

2019-10-25 10:28 UTC, jehy commented on bin/slack-bot.js
> +    fn: (el) => !slackCfg.errNotifyBot.blackListMsgNames.includes(el.msgName),
кажется, здесь лишнее отрицание

2019-10-25 10:29 UTC, jehy commented on bin/slack-bot.js
> +  importantErr: {
Насколько я вижу,у  тебя теперь одинаково репортятся те ошибки, которые возросли, и те, которые возникли впервые, да? Если да, то это плохо - очень важно знать, что ошибка свежая.

2019-10-25 12:02 UTC, jehy requested changes

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +  importantErr: {
Можно, например, добавить поле "замечена впервые", которые будет только если оно есть.
Кстати, про стедж тоже стоит просто добавлять только когда это стейдж, "стейдж нет" - мало осмысленно.

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +function getDuty() {
1) Promise.resolve тут не нужен
2) для понятности я бы сделал getDuty как async function, и написал бы обращение к слак апи через эвейт.
3) Не нужно искать никаких волшебных строчек типа Avia Dev, просто регуляркой вынимай всех людей из топика, как в Анечке.

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +    fn: (el) => !slackCfg.errNotifyBot.blackListMsgNames.includes(el.msgName),
кажется, здесь лишнее отрицание

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +  const half = slackCfg.errNotifyBot.maxSlackMessages / 2;
не понял, зачем этот half

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +const isExpiredTime = (time) => moment(moment().diff(time)).minute() > slackCfg.errNotifyBot.diffMinutesBetweenSendSlack;
лучше функции объявлять как функции - хотя бы ради единообразия.

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +  if (elements.length < 0) {
Эээ, вряд ли когда-нибудь у массива будет отрицательная длина.....

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +    if (!resQuery[0] || (resQuery[0] && isExpiredTime(resQuery[0].added))) {
таки я уже писал. Вместо того, чтобы брать последний элемент и затем сравнивать его в JS - делай это сразу в СУБД.

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +      log.info(`Error is exist in base & time not expired ${JSON.stringify(el)}`);
Error exists

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +  await Promise.each(elements, async (el) => {
тут лучше подойдёт Promise.reduce

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +    if (!resQuery[0] || (resQuery[0] && isExpiredTime(resQuery[0].added))) {
Кстати, чтобы не брать нулевой элемент - используй http://knexjs.org/#Builder-first - выглядеть будет гораздо лучше.

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +setInterval(() => {
видимо, я тебе несколько перегрузил инфой.
Я говорил, что можно использовать setInterval вместо крона - но так же говорил, что лучше делать такие штуки не через шедулер, а через рекурсивный вызов с таймаутами.

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +      const duty = await getDuty();
наверное, имеет смысл получать текущего дежурного только если мы нашли какие-то ошибки для показа.

2019-10-25 12:02 UTC, jehy commented on modules/showTopErrors.js
> +    }).then((result) => Promise.resolve({topErrors: result, fetchErrors}));
Promise.resolve здесь совершенно не нужен

2019-10-25 12:02 UTC, jehy commented on bin/slack-bot.js
> +  {name: 'showTopErrors', data: { env: '', period: 'day', role: '', pid: '', index: 'twapi-avia'}, id: uuidv4()},
ты же вроде этот id нигде не используешь, зачем он тогда?

2019-10-25 14:55 UTC, LoginovKonstantin reviewed
Где не ответил буду править

2019-10-25 14:55 UTC, LoginovKonstantin commented on bin/slack-bot.js
> +    fn: (el) => !slackCfg.errNotifyBot.blackListMsgNames.includes(el.msgName),
Нет

2019-10-25 14:55 UTC, LoginovKonstantin commented on bin/slack-bot.js
> +function getDuty() {
2. no return await, если сделать в переменную, то линтер сам хочет конвертировать в return await, а потом снова начинает no return await и так цикл, решил поэтому сделать так

2019-11-05 16:02 UTC, jehy requested changes

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +      && (el.preHour === 0 ? el.count : (el.count / el.preHour).toFixed(2)) >= slackCfg.errNotifyBot.perHourErrors
непонятно, почему тут может возвратиться el.count - если в ответе ожидается boolean. Наверное, там true должно было быть. Но тогда проще это записать без тернарника. Кстати, округление тоже лишнее. Судя по всему, копи паста из куска ниже.

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +      && moment(el.firstMet).startOf('day').toString() === moment().startOf('day').toString()
Какая-то слишком глубокая мысль. Проще
moment(el.firstMet).format('DDMMYYYY')====moment().format('DDMMYYYY')

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +function getDuty() {
сделай и покажи на что ругается линтер. Наверняка это можно решить лучше : )

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +        if (!value || (value && isExpiredTime(value.added))) {
Ещё раз. Время проверять через базу. Не получается - напиши что не получается. Что ж молча вот так писать : (

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +      .from(slackCfg.table)
табличку можно писать в код, без конфига. сложно придумать  кейс, когда внесение её в конфиг имеет какой-то смысл.

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +  if (elements.length < 1) {
как-то логичнее сравнивать или с нулём или делать проверку на falsy

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +      .then(async (value) => {
зачем мешать промисы с асинк эвейтом?Сделать это последовательными эвейт операциями.

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +        ...(_.remove(whiteList, filters.firstErrors.fn)).map((obj) => ({ ...obj, typeErr: 'firstErrors'})),
вместо этой стрёмной конструкции можно профти по массиву редьюсом. И ничего не удалять - если ошибка прошла по более приоритетному признаку, то по менее проритетному она уже не пройдёт.

2019-11-05 16:02 UTC, jehy commented on migrations/20191022230300_slack_bot.js
> +    t.string('msgName').nullable();
тут тоже notNullable - если его нет, мы его всё равно сгенерим )

2019-11-05 16:02 UTC, jehy commented on migrations/20191022230300_slack_bot.js
> +const table = 'slack_bot';
вот тут кстати ты берёшь не из конфига ;)
Но, как я сказал, и не надо в конфиг имя таблицы класть.

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +           ${el.env === 'staging' ? ' на стейдже' : ''}`.replace((/ {2}|\r\n|\n|\r/gm), ''),
регулярки для того, чтобы побороть форматирование, которое задано в коде? Чёт перебор. Можно просто не форматировать строку в коде. Например, вместо строковых литералов просто использовать конкотенацию.

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +  const result = messages.reduce((acc, cur) => {
чтобы не запушить одну и ту жу ошибку в несколько разных массивов, можно добавить ретурнов.

2019-11-05 16:02 UTC, jehy commented on bin/slack-bot.js
> +  const res = [...result.firstErrors, ...result.growingErrors, ...result.staging, ...result.other];
Arra.concat здесь как-то логичнее деструкторов выглядел бы. И лаконичнее.

2019-11-05 16:02 UTC, jehy commented on package.json
> +    "lodash": "^4.17.15",
лодаш мы стараемся не использовать без особых уважительных причин. Если интересно, почему - могу отдельно рассказать в слак, или может даже созвоном. Хотя можешь попробовать сначала ребят спросить.

2019-11-06 07:27 UTC, kotAndEgor commented on bin/slack-bot.js
> +        if (!value || (value && isExpiredTime(value.added))) {
Так я написал в задаче в комментарии ведь

2019-11-07 14:30 UTC, jehy requested changes

2019-11-07 14:30 UTC, jehy commented on bin/slack-bot.js
> +const FIRST_ERRORS = 'firstErrors';
чтобы не разводить кучу констант, проще завести объект с енамами под одно и то же назначение.

2019-11-07 14:30 UTC, jehy commented on bin/slack-bot.js
> +      const grow = (el.preHour === 0 ? el.count : (el.count / el.preHour).toFixed(2)) >= slackCfg.errNotifyBot.perHourErrors;
не вижу изменений по замечанию : (
В тему о том, что там должен быть булеан, и округление не нужно.

2019-11-07 14:30 UTC, jehy commented on bin/slack-bot.js
> +      text: `*Статистика.* Уважаемые дежурные ${duty[0]}, ${duty[1]}, у нас что-то горит...`,
лучше не хардкодить количество, а просто массив выводить. Вдруг их будет 1. Или 3 ))

2019-11-07 14:30 UTC, jehy commented on bin/slack-bot.js
> +  const limit = slackCfg.errNotifyBot.maxSlackMessages / keys.length;
наверное, следует здесь округлять - иначе делать потом слайс по дробному числу как-то стрёмно, даже если работает.

2019-11-07 14:30 UTC, jehy commented on bin/slack-bot.js
> +  return moment(moment().diff(time)).minute() > slackCfg.errNotifyBot.diffMinutesBetweenSendSlack;
а ты упорный : ) Но всё же нет, не надо это считать на клиенте )

2019-11-07 14:30 UTC, jehy commented on config/default.json
> +      "blackListMsgNames": [""],
лучше всё же пустй массив, а не массив с пустой строкой

2019-11-07 14:30 UTC, jehy commented on bin/slack-bot.js
> +  setInterval(() => run(), TIME_OUT);
Мы ж с тобой обсуждали, что такие штуки надо через таймаут после выполнения делать, а не через интервал...
Или не с тобой?

2019-11-07 14:30 UTC, jehy commented on bin/slack-bot.js
> +function getDuty() {
не вижу изменений, не вижу, чтобы ты мне показал, что там не так.

2019-11-07 14:30 UTC, jehy commented on bin/slack-bot.js
> +    acc[el] = [].concat(object[el].slice(0, limit));
зачем тут пустой массив? слайс и так делает шеллоу копи.

2019-11-07 14:30 UTC, jehy commented on bin/slack-bot.js
> +      const assembledObject = errors.reduce((acc, el) => {
чёт очень сложно.
я говорил о том, что можно делать цикл по ошибкам, в нём цикл по условиям в порядке приоритета (typesConfig) - и при первом попадании в соответствии выходить из внутреннего цикла, чтобы не репортить ошибку есколько раз по менее приоритетным условиям.

Здесь мне кажется какой-то сложный код, и не вижу дедупликации.

2019-11-07 16:06 UTC, LoginovKonstantin reviewed
Где не откоментил поправил

2019-11-07 16:06 UTC, LoginovKonstantin commented on bin/slack-bot.js
> +      const grow = (el.preHour === 0 ? el.count : (el.count / el.preHour).toFixed(2)) >= slackCfg.errNotifyBot.perHourErrors;
const el = {}
el.preHour = 1;
el.count = 2;
(el.preHour === 0 ? el.count : (el.count / el.preHour).toFixed(2)) >= 0

>> true

2019-11-07 16:06 UTC, LoginovKonstantin commented on bin/slack-bot.js
> +      const grow = (el.preHour === 0 ? el.count : (el.count / el.preHour).toFixed(2)) >= slackCfg.errNotifyBot.perHourErrors;
'>=' 5 
>> false

2019-11-07 16:06 UTC, LoginovKonstantin commented on bin/slack-bot.js
> +  setInterval(() => run(), TIME_OUT);
Так из анечки взято вроде) Или я куда-то не туда посмотрел

2019-11-07 16:06 UTC, kotAndEgor commented on bin/slack-bot.js
> +  setInterval(() => run(), TIME_OUT);
Там в индексжс тоже самое
`const updateInterval = 1000 * 60 * (config.updateInterval || 5);// from config or every 5 minutes
// const updateInterval = 1000 * 20;// every 60 second
async function run() {
  try {
    await Promise.all([fetchTimeTables(), fetchUsers(), fetchSlackUsers(), fetchSlackConversations()]);
    return updateSlack();
  } catch (err) {
    log.error(`ERR: ${err}`);
    return false;
  }
}

async function start() {
  await run();
  setInterval(() => run(), updateInterval);
}

start();`

2019-11-07 16:06 UTC, kotAndEgor commented on bin/slack-bot.js
> +      const assembledObject = errors.reduce((acc, el) => {
А что есть дубль? Одинаковые ошибки но на разных окружениях это дубли? Я что-то подзабыл(

2019-11-07 16:06 UTC, kotAndEgor commented on bin/slack-bot.js
> +      const assembledObject = errors.reduce((acc, el) => {
На счет дублей жду ответа. Зато теперь эта штука кастомизируется с помощью одного объекта. Можно добавлять и удалять новые типы ошибок и ничего не должно сломаться)

2019-11-08 10:35 UTC, jehy requested changes

2019-11-08 10:35 UTC, jehy commented on bin/slack-bot.js
> +      const grow = (el.preHour === 0 ? el.count : (el.count / el.preHour).toFixed(2)) >= slackCfg.errNotifyBot.perHourErrors;
Ещё раз.
grow это по сути boolean.
В случае el.preHour === 0 ты возвращаешь число. Зачем?
И зачем округлять el.count / el.preHour перед сравнением?

2019-11-08 10:35 UTC, jehy commented on bin/slack-bot.js
> +        .andWhere('added', '>', moment(new Date()).subtract(minutes, 'minutes').toDate())
Почти. Но лучше
```
      .whereRaw(`added > DATE_SUB(NOW(), INTERVAL ${slackCfg.errNotifyBot.diffMinutesBetweenSendSlack} MINUTES)`)
```
Так ты полностью уходишь от какой-либо работы с временем на клиенте, и тебе становится пофигу, какие на нём настройки - роляет только время в базе.

2019-11-08 10:35 UTC, jehy commented on bin/slack-bot.js
> +      const assembledObject = errors.reduce((acc, el) => {
Под дублями я имею в виду когда у тебя одна и та же ошибка репортится в нескольких секциях - например, она и только сегодня возникла, и эпически выросла.
Очевидно, что если у нас отработало правило на ошибку по хотя бы одной причине, то дальше её обрабатывать не надо.

2019-11-08 10:35 UTC, jehy commented on bin/slack-bot.js
> +  setInterval(() => run(), TIME_OUT);
Посмотрел туда, но там сделано неправильно : ) Исправлю.
так мы с тобой или нет обсуждали про то, почему кроны и интервалы это плохо?

2019-11-08 10:35 UTC, jehy commented on config/default.json
> +      "blackListMsgNames": [""],
осталось

2019-11-08 10:35 UTC, jehy commented on bin/slack-bot.js
> +const TIME_OUT = slackCfg.errNotifyBot.intervalMin * 1000 * 60;
слово TIMEOUT пишется в одно слово, это не время вне : )

2019-11-08 11:09 UTC, kotAndEgor commented on bin/slack-bot.js
> +  setInterval(() => run(), TIME_OUT);
Да, мы говорили про кроны и интервалы, но как сделать через таймаут я не очень понял, потом ты сказал посмотреть в анечке, я посмотрел, увидел что там интервал, показалось странным, теперь он тут)

2019-11-08 11:09 UTC, kotAndEgor commented on bin/slack-bot.js
> +      const grow = (el.preHour === 0 ? el.count : (el.count / el.preHour).toFixed(2)) >= slackCfg.errNotifyBot.perHourErrors;
Чет затупил, долго пытался понять)

2019-11-08 11:09 UTC, kotAndEgor commented on bin/slack-bot.js
> +      const assembledObject = errors.reduce((acc, el) => {
Посмотрю внимательно

2019-11-08 11:34 UTC, bollwar404 commented on bin/slack-bot.js
> +const Errors = {
А нужно ли оно?

Пока что вижу что просто создается объект для того чтоб на основе него создать другой...

2019-11-08 11:40 UTC, bollwar404 commented on bin/slack-bot.js
> +  const link = (m) => (makeKibanaLink('twapi-avia', m.name, m.msgName, kibana.url));
Нужно ли создавать эти 3 функи при каждом вызове `generateBlocks`

2019-11-08 11:54 UTC, bollwar404 commented on bin/slack-bot.js
> +  if (keys.length === 0) {
!keys.length

Но, вкусовщина

2019-11-08 12:01 UTC, bollwar404 commented on bin/slack-bot.js
> +  // На уровне массива объектов
Комменты, кмк, немного неявные и необъясняют что и зачем.

2019-11-08 12:31 UTC, kotAndEgor commented on bin/slack-bot.js
> +const Errors = {
Шоб оперировать переменными а не строками, в которых можно ошибиться

2019-11-08 12:41 UTC, bollwar404 commented on bin/slack-bot.js
> +const Errors = {
Дык если они у тебя в одном месте - ты будешь иметь такие же шансы на ошибку как и в данный момент

2019-11-11 13:02 UTC, kotAndEgor commented on bin/slack-bot.js
> +const Errors = {
Сразу понятно, какие ошибки могут быть, как добавить и как удалить

2019-11-11 13:02 UTC, kotAndEgor commented on bin/slack-bot.js
> +  if (keys.length === 0) {
Тут явно зато)

2019-11-11 13:02 UTC, kotAndEgor commented on bin/slack-bot.js
> +      const assembledObject = errors.reduce((acc, el) => {
Поправил на for с break, дубляжей быть не должно

2019-11-15 14:08 UTC, jehy commented on bin/slack-bot.js
> +  if (keys.length === 0) {
мне тоже больше нравится сравнение с нулём : )

2019-11-15 14:12 UTC, jehy commented on bin/slack-bot.js
> +  setInterval(() => run(), TIMEOUT);
таймаут

2019-11-15 14:17 UTC, jehy requested changes

2019-11-15 14:17 UTC, jehy commented on bin/slack-bot.js
> +  [Errors.STAGING_ERRORS]: {
Тэк, видимо, я плохо пояснил, что именно нам нужно.
Нам неинтересны просто стейдж ошибки.
И "другие" ошибки тоже.

Нам интересны стейдж ошибки по тем же признакам что и продовые - то есть те которые сильно выросли, или те которые появились впервые.

Просто хочется их отделить, чтобы быстро понимать, что это скорее всего проблема релиза.

Идея понятна?

2019-11-15 14:29 UTC, kotAndEgor commented on bin/slack-bot.js
> +  [Errors.STAGING_ERRORS]: {
Теперь вроде да)

2019-11-28 13:29 UTC, merged