Add 'like' for sql query
jehy/shodan pull request #16
Opened 2019-12-07 18:16 UTC by kotAndEgor

2019-12-07 19:52 UTC, jehy commented
Мысль правильная, но реализация не совсем.
На продакшн сервере довольно данных, и поиск по неточному соотвествию будет идти слишком тяжело.
Если кстати вообще будет - потому что там поле Enum, а не String...

В общем, надо это через IN решить, а не LIKE.

2019-12-07 19:52 UTC, jehy requested changes
Мысль правильная, но реализация не совсем.
На продакшн сервере довольно данных, и поиск по неточному соотвествию будет идти слишком тяжело.
Если кстати вообще будет - потому что там поле Enum, а не String...

В общем, надо это через IN решить, а не LIKE.

2019-12-07 21:32 UTC, kotAndEgor commented
logs -> enum
first_last_met -> varchar
Как так получилось - не понятно

2019-12-09 14:41 UTC, kotAndEgor commented
Обновил

2019-12-09 15:05 UTC, jehy requested changes

2019-12-09 15:05 UTC, jehy commented on modules/showTopErrors.js
> +    const env = event.data.env === 'production' ? ['production-a', 'production-b'] : ['staging'];
На случай, если будут какие-то другие энвы, лучше здесь не staging указывать, а прямо значение переменной.

Кстати, если data.env = production-a, то тоже не сработает и покажет стейдж.

2019-12-09 15:05 UTC, jehy commented on modules/showTopErrors.js
> +    const env = event.data.env === 'production' ? ['production-a', 'production-b'] : ['staging'];
то же самое

2019-12-09 15:05 UTC, jehy commented on modules/showTopErrors.js
> +  if (event.data.env === 'production') {
Здесь тоже лучше сделать через whereIn - красисивее и быстрее.

2019-12-09 15:05 UTC, jehy commented on modules/showTopErrors.js
> +    const env = event.data.env === 'production' ? ['production-a', 'production-b'] : ['staging'];
ну ты понял

2019-12-09 15:13 UTC, kotAndEgor commented on modules/showTopErrors.js
> +    const env = event.data.env === 'production' ? ['production-a', 'production-b'] : ['staging'];
Ну так, мы должны под все случаи подстроиться чтоли? Я думал на prod и stage разделить надо, как и сказано в задаче. Ну или можно инверсировать условие!

2019-12-09 15:38 UTC, jehy commented on modules/showTopErrors.js
> +    const env = event.data.env === 'production' ? ['production-a', 'production-b'] : ['staging'];
Ну на морде ж есть выбор между стейджем и двумя продакшнами. Ты его ломаешь этой правкой.

2019-12-10 11:59 UTC, jehy requested changes
комментарии в слаке

2019-12-11 09:13 UTC, merged